#!/bin/bash
sudo pacman -S haveged
sudo systemctl enable haveged
sudo systemctl start haveged
sudo pacman-key --init
sudo pacman-key --populate archlinux
sudo pacman -Syy

sudo pacman -S archlinux-wallpaper openbox pcmanfm clipit lxdm lxpanel lxappearance-obconf python2-xdg oblogout synapse plank leafpad file-roller ntfs-3g dosfstools gvfs gnome-themes-standard firefox ristretto xdg-user-dirs xcompmgr xfce4-power-manager xfce4-terminal xdotool p7zip unzip zip unrar gtk-engine-murrine numlockx --noconfirm
xdg-user-dirs-update
sudo updatedb
mkdir -p ~/.config/openbox
cp -R /etc/xdg/openbox/* ~/.config/openbox
ln -s ~/.config/openbox openbox
sudo systemctl enable lxdm
sudo gpasswd -a $USER vboxsf
